---
#commented out irrelevant nodes
nodes:
# - _definitions
# - _settings
# - _terms
- acknowledgement
- administration_meta_data
- baseline_demographics
- center
# - core_metadata_collection
- data_release
- demographic
- environment
- follow_up
- health
- implementation_outcome_measures
- justice_involvement_questionnaire
- keyword
# - metaschema
- moud_questionnaire
- organization
- organizational_climate_stress
- organizational_readiness
- oud
- participant
- practitioner
- program
# - project
# - project_metadata
- promis
- protocol
- publication
- recovery
# - reference_file
- risk_of_harm_and_consequences
# - root
- serious_adverse_event
- staff_attitudes_toward_moud
- substance_use
- system
- treatment_preferences_questionnaire
- utilization_services_questionnaire
