#https://www.mkdocs.org/user-guide/configuration/#
site_name: JCOIN Data Commons Documentation
site_url: https://jcoin-maarc.github.io/jdc-docs-public
nav:
  - Home: index.md
  - Return to Platform: https://jcoin.datacommons.io/
  - Logging In: logging-in.md
  - JDC Platform Features:
    - Home Page: platform/homepage.md
    - Explorer Page: platform/explorer.md
    - Profile Page: platform/profile_page.md
  - Core Measures:
    - Data Dictionary Search: https://jcoin-maarc.github.io/JCOIN-Core-Measures
  - Curation and Submission Tools: https://github.com/jcoin-maarc/jdc-utilities #NOTE: this will be the git hub pages after its built
  - Contact: contact.md
theme:
  name: material
  palette:
    scheme: jdc
  font:
    text: Source Sans Pro
  logo: assets/heal_logo.png
  features:
    - navigation.indexes
    # Disable for now, as it causes problems with links to sections in Safari
    # https://github.com/squidfunk/mkdocs-material/issues/3797
    # - navigation.instant
    - navigation.indexes
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.tracking
    #- navigation.sections
    #- toc.integrate
  favicon: assets/heal_logo.png
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://jcoin.datacommons.io/
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      url_download: True
plugins:
  - search
  - mkdocs-video:
      is_video: True
  # - mermaid2
  #- offline