#https://www.mkdocs.org/user-guide/configuration/#
site_name: JCOIN Data Commons Documentation
site_url: https://jcoin-docs-dev.io
nav:
  - Home: ./index.md
  - Submission for Hubs: submission.md
  - JCOIN Variables:
    - Overview: nodes/README.md
    - Acknowledgement: nodes/acknowledgement.md
    - Administration Meta Data: nodes/administration_meta_data.md
    - Baseline Demographics: nodes/baseline_demographics.md
    - Center: nodes/center.md
    #- Core Metadata Collection: nodes/core_metadata_collection.md
    - Data Release: nodes/data_release.md
    - Demographic: nodes/demographic.md
    - Environment: nodes/environment.md
    - Follow Up: nodes/follow_up.md
    - Health: nodes/health.md
    - Implementatition Outcome Measures: nodes/implementation_outcome_measures.md
    - Justice Involvement Questionnaire: nodes/justice_involvement_questionnaire.md
    - Keyword: nodes/keyword.md
    #- GDC JSON schema extension: nodes/metaschema.md
    - MOUD Lifetime/Past Month Use Questionnaire: nodes/moud_questionnaire.md
    - Organization: nodes/organization.md
    - Organizational Climate Stress: nodes/organizational_climate_stress.md
    - ORGANIZATIONAL READINESS FOR IMPLEMENTING CHANGE (ORIC): nodes/organizational_readiness.md
    - OUD: nodes/oud.md
    - Participant: nodes/participant.md
    - Practitioner: nodes/practitioner.md
    - Program: nodes/program.md
    #- Project: nodes/project.md
    #- Project Metadata: nodes/project_metadata.md
    - PROMIS: nodes/promis.md
    - Protocol: nodes/protocol.md
    - Publication: nodes/publication.md
    - Recovery: nodes/recovery.md
    #- Reference File: nodes/reference_file.md
    - Risk of Harm and Consequences: nodes/risk_of_harm_and_consequences.md
    #- Root: nodes/root.md
    - Serious Adverse Event: nodes/serious_adverse_event.md
    - Staff Attitudes Toward MOUD: nodes/staff_attitudes_toward_moud.md
    - Substance Use: nodes/substance_use.md
    - System: nodes/system.md
    - Treatment Preferences Questionnaire: nodes/treatment_preferences_questionnaire.md
    - Utilization of Services Questionnaire: nodes/utilization_services_questionnaire.md
  - Opioid Policy Scan:
    - OEPS in the JDC: oeps.md
    - Overview: oeps/README.md
    - 7-day Average Case Count: oeps/COVID.md
    - Access to Health Centers: oeps/Access_FQHCs_MinDistance.md
    - Access to Hospitals: oeps/Acesss_Hospitals_MinDistance.md
    - Access to MOUDs: oeps/Access_MOUDs.md
    - Access to Mental Health Providers: oeps/Access_MentalHealth_MinDistance.md
    - Access to Pharmacies: oeps/Access_Pharmacies_MinDistance.md
    - Adjusted Case Count per 100K: oeps/COVID.md
    - Age: oeps/Age_2018.md
    - Alcohol Outlet Density: oeps/AlcoholOutlets_2018.md
    - Crosswalk files: oeps/crosswalk.md
    - Cumulative Case Count: oeps/COVID.md
    - Drug-related death rate: oeps/Health_DrugDeaths.md
    - Educational Attainment: oeps/Other_Demographic_2018.md
    - Employment Trends: oeps/Job_Categories_byIndustry_2018.md
    - Essential Worker Jobs: oeps/Job_Categories_byOccupation_2018.md
    - Foreclosure Rate: oeps/ForeclosureRate.md
    - Geographic Boundaries: oeps/GeographicBoundaries_2018.md
    - Good Samaritan Laws: oeps/GSL_2018.md
    - Group Quarter: oeps/GroupQuar.md
    - Hepatitis C rates: oeps/HepC_rate.md
    - Historical 7-day Average Adjusted Case Count per 100K: oeps/COVID.md
    - Homeless Population: oeps/HomelessPop.md
    - Housing Occupancy Rate: oeps/Housing_2018.md
    - Housing Unit Density: oeps/Housing_2018.md
    - Housing Vacancy Rate: oeps/Housing_2018.md
    - Hypersegregated Cities: oeps/Overlay.md
    - Jail Incarceration Rates: oeps/Jail variables_2017.md
    - Long Term Occupancy: oeps/Housing_2018.md
    - Medicaid Expansion: oeps/MedExpan_2018.md
    - Medicaid Expenditure: oeps/MedExp_2019.md
    - Medical Marijuana Laws: oeps/MedMarijLaw.md
    - Mobile Homes: oeps/Housing_2018.md
    - Naloxone Access Laws: oeps/NAL_2017.md
    - Native American Reservations: oeps/Overlay.md
    - Per Capita Income: oeps/Economic_2018.md
    - Physicians: oeps/Health_PCPs.md
    - Population with a Disability: oeps/Other_Demographic_2018.md
    - Poverty Rate: oeps/Economic_2018.md
    - Prescription Drug Monitoring Programs (PDMP): oeps/PDMP_2017.md
    - Prison Incarceration Rates: oeps/Prison variables_2016.md
    - Race & Ethnicity: oeps/Race_Ethnicity_2018.md
    - Rental Rates: oeps/Housing_2018.md
    - Residential Segregation Indices: oeps/Residential_Seg_Indices.md
    - Social Determinants of Health (SDOH): oeps/SDOH_2014.md
    - Social Vulnerability Index (SVI): oeps/SVI_2018.md
    - Southern Black Belt: oeps/Overlay.md
    - State & Local Government Expenditures: oeps/PublicExpenditures.md
    - Syringe Services Laws: oeps/Syringe.md
    - Unemployment Rate: oeps/Economic_2018.md
    - Urban/Suburban/Rural Classification: oeps/Rural_Urban_Classification_T_Z.md
    - Veteran Population: oeps/VetPop.md
    - Access to Opioid Treatment Programs: oeps/Access_OpioidUseTreatment.md
    - Access to Substance Use Treatment Facilities: oeps/Access_SubstanceUseTreatment.md
  - Amerispeak Stigma Survey: stigma.md
# theme:
#   name: readthedocs
#   include_sidebar: true
use_directory_urls: true
markdown_extensions:
    - toc:
        permalink: "##"
plugins:
  - search
  - mermaid2