#https://www.mkdocs.org/user-guide/configuration/#
site_name: JCOIN Data Commons Documentation
site_url: https://norc-heal.github.io/jdc-docs-public
nav:
  - About the JDC: ./index.md
  - Future development: future/todos.md
use_directory_urls: true
markdown_extensions:
    - toc:
        permalink: "##"
plugins:
  - search
  - mermaid2
  #- offline