#https://www.mkdocs.org/user-guide/configuration/#
site_name: JCOIN Data Commons Documentation
site_url: https://jcoin-docs-dev.io
nav:
  - Home: ./index.md
  - Data: data/data.md
  - Hub Submissions: submission/submission_public.md
  - Hub Core measure Data Dictionaries:
    - Baseline Measure Fields: submission/baseline_fields.md
    - Follow up measures (i.e., all time points) Fields: submission/time_point_fields.md
  - Future development: future/todos.md
use_directory_urls: true
markdown_extensions:
    - toc:
        permalink: "##"
plugins:
  - search
  - mermaid2
  #- offline